//! Managed Agent contributions and adapters for the existing Codex host.

mod binding;
mod checkpoints;
mod context;
mod hook_executor;
mod host;
mod input;
mod process_activity;
mod process_audit;
mod publication;
mod rpc;
mod store;
mod store_audit;
mod thread;
mod tool_activity;
mod tool_audit;
mod tool_workspace;
mod workspace_gate;
mod workspace_operations;

pub use checkpoints::WorkspaceCheckpoints;
pub use context::AgentContext;
pub use hook_executor::RecordedHookExecutor;
pub use host::AgentAccountSource;
pub use host::AgentHostConfig;
pub use host::AgentHostGeneration;
pub use host::AgentHostPrograms;
pub use host::AgentLoadedConfig;
pub use host::AgentPreparationConfig;
pub use host::HostArchiveJobIds;
pub use host::HostArchiveJobs;
pub use host::HostArchivePhase;
pub use host::HostArchiveReceipts;
pub use host::HostAuditPositions;
pub use host::HostShutdownJournal;
pub use host::HostShutdownPlan;
pub use host::HostShutdownStatus;
pub use host::ManagedHost;
pub use host::ManagedHostServices;
pub use host::NativeAccountBootstrap;
pub use host::PreparedAgentHost;
pub use host::StartedAgentHost;
pub use input::AgentMessageInput;
pub use process_activity::ProcessActivity;
pub use process_activity::ProcessSettlement;
pub use process_activity::ProcessSettlementOutcome;
pub use process_audit::ProcessAudit;
pub use process_audit::ProcessAuditEvent;
pub use process_audit::RecordedProcessOutput;
pub use rpc::AgentRpc;
pub use rpc::AgentRpcOutcome;
pub use store::AuditedThreadStore;
pub use store_audit::StoreAudit;
pub use store_audit::StoreAuditEvent;
pub use store_audit::StoreAuditIdentity;
pub use store_audit::StoreAuditPage;
pub use store_audit::StoreAuditRecord;
pub use thread::AgentThread;
pub use thread::AgentThreadOutcome;
pub use tool_activity::ToolActivity;
pub use tool_activity::ToolSettlement;
pub use tool_audit::RecordedToolPayload;
pub use tool_audit::ToolAudit;
pub use tool_audit::ToolAuditEvent;
pub use tool_audit::ToolOperation;
pub use tool_audit::ToolOrigin;
pub use tool_audit::ToolOutcome;
pub use tool_workspace::ToolWorkspace;
pub use workspace_gate::WorkspaceGate;
pub use workspace_gate::WorkspaceLease;
pub use workspace_operations::WorkspaceOperations;
