load("@crates//:defs.bzl", "all_crate_deps")
load("@rules_rust//rust:defs.bzl", "rust_binary", "rust_library")

rust_library(
    name = "provider",
    srcs = glob(
        ["src/**/*.rs"],
        exclude = ["src/bin/**/*.rs"],
    ),
    crate_name = "codex_infra_provider",
    edition = "2024",
    visibility = ["//visibility:public"],
    deps = all_crate_deps(),
)

rust_binary(
    name = "codex-infra-account",
    srcs = ["src/bin/codex-infra-account.rs"],
    crate_name = "codex_infra_account",
    crate_root = "src/bin/codex-infra-account.rs",
    edition = "2024",
    visibility = ["//visibility:public"],
    deps = [":provider"] + all_crate_deps(),
)
