[package]
name = "codex-infra-provider"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
doctest = false
test = false

[lints]
workspace = true

[dependencies]
async-stream = { workspace = true }
bytes = { workspace = true }
eventsource-stream = { workspace = true }
futures = { workspace = true, features = ["std"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
